import type { StickyColumnConfig, TableConfig } from "@/components/tables/core"
import type { TableId } from "./table-settings"

export const STICKY_COLUMNS: Record<TableId, StickyColumnConfig[]> = {
  members: [
    { id: "select", width: 50 },
    { id: "member", width: 320 },
  ],
  contributions: [{ id: "member", width: 300 }],
  charges: [{ id: "name", width: 300 }],
  shares: [{ id: "effectiveFrom", width: 180 }],
  business: [
    { id: "select", width: 50 },
    { id: "business", width: 320 },
  ],
  shareApplications: [
    { id: "select", width: 50 },
    { id: "application", width: 320 },
  ],
  procurement: [
    { id: "select", width: 50 },
    { id: "request", width: 320 },
  ],
  foodPurchase: [
    { id: "select", width: 50 },
    { id: "application", width: 320 },
  ],
  projectFinancing: [
    { id: "select", width: 50 },
    { id: "request", width: 320 },
  ],
  support: [
    { id: "select", width: 50 },
    { id: "case", width: 340 },
  ],
  paymentReceipts: [
    { id: "select", width: 50 },
    { id: "receipt", width: 320 },
  ],
  chargeLibrary: [{ id: "charge", width: 300 }],
  imports: [{ id: "import", width: 300 }],
  loanPortfolio: [{ id: "member", width: 300 }],
  loanRequests: [{ id: "member", width: 300 }],
  membershipApprovals: [{ id: "applicant", width: 300 }],
  monthlyRecords: [{ id: "member", width: 300 }],
  notifications: [{ id: "subject", width: 320 }],
  audit: [{ id: "action", width: 300 }],
}

export const SORT_FIELD_MAPS: Record<TableId, Record<string, string>> = {
  members: {
    member: "fullName",
    number: "memberNumber",
    status: "status",
    kyc: "kycStatus",
  },
  contributions: {
    member: "memberName",
    savings: "amount",
    committed: "committedAmount",
    extraSavings: "extraSavingsAmount",
    posted: "postedAt",
  },
  charges: {
    name: "name",
    chargeFrequency: "chargeFrequency",
    "currentVersion.amount": "currentAmount",
    chargeValueType: "chargeValueType",
    versions: "versionCount",
    isActive: "isActive",
  },
  shares: {
    effectiveFrom: "effectiveFrom",
    valueType: "valueType",
    amount: "amount",
    notes: "notes",
    isCurrent: "isCurrent",
  },
  business: {
    business: "name",
    capital: "capitalAmount",
    period: "startDate",
    profit: "profitAmount",
    status: "status",
  },
  shareApplications: {
    application: "memberName",
    status: "status",
    units: "requestedUnits",
    value: "shareValueSnapshot",
    requestedAt: "createdAt",
    notes: "notes",
    reviewNotes: "reviewNotes",
  },
  procurement: {
    request: "itemName",
    status: "status",
    requested: "requestedCost",
    approved: "approvedCost",
    monthly: "estimatedMonthlyRepayment",
    schedule: "outstandingAmount",
    requestedAt: "requestedAt",
    vendor: "vendorName",
  },
  foodPurchase: {
    application: "memberName",
    status: "status",
    requested: "requestedAmount",
    approved: "approvedAmount",
    payment: "paidAmount",
    requestedAt: "requestedAt",
    item: "itemDescription",
  },
  projectFinancing: {
    request: "businessName",
    status: "status",
    requested: "requestedAmount",
    approved: "approvedAmount",
    monthly: "estimatedMonthlyPayback",
    requestedAt: "requestedAt",
    disbursed: "disbursedAt",
  },
  support: {
    case: "subject",
    status: "status",
    category: "category",
    priority: "priority",
    assignee: "assignedToUser",
    latestReply: "latestReply",
    linkedRecord: "linkedRecord",
    createdAt: "createdAt",
  },
  paymentReceipts: {
    receipt: "memberName",
    status: "status",
    amount: "totalAmount",
    paidAt: "paidAt",
    submittedAt: "submittedAt",
    allocations: "allocationCount",
    reference: "paymentReference",
  },
  chargeLibrary: {
    charge: "name",
    status: "isActive",
    kind: "kind",
    effectiveFrom: "currentEffectiveFrom",
    amount: "amount",
  },
  imports: {
    import: "importType",
    status: "status",
    rows: "totalRows",
    review: "reviewCount",
    createdBy: "createdBy",
    createdAt: "createdAt",
  },
  loanPortfolio: {
    member: "memberName",
    loan: "loanProductName",
    status: "status",
    servicing: "estimatedMonthlyServicing",
  },
  loanRequests: {
    member: "memberName",
    request: "requestedAt",
    status: "status",
    review: "reviewStatus",
  },
  membershipApprovals: {
    applicant: "fullName",
    number: "memberNumber",
    phone: "phoneNumber",
    verification: "emailVerifiedAt",
    status: "status",
    submitted: "submittedAt",
  },
  monthlyRecords: {
    member: "memberName",
    balance: "currentBalance",
    loanStatus: "loanStatus",
    savings: "contributionAmount",
    shareCharge: "shareChargeAmount",
    loanDue: "loanRepaymentAmount",
    payable: "totalPayableAmount",
    paid: "totalPaidAmount",
    charges: "allChargesAmount",
    finalIncome: "finalIncomeAmount",
    status: "status",
  },
  notifications: {
    subject: "subject",
    recipient: "recipient",
    type: "notificationType",
    status: "status",
    createdAt: "createdAt",
  },
  audit: {
    action: "action",
    actor: "actor",
    entity: "entityType",
    occurredAt: "occurredAt",
  },
}

export const NON_REORDERABLE_COLUMNS: Record<TableId, Set<string>> = {
  members: new Set(["select", "member", "actions"]),
  contributions: new Set(["member", "actions"]),
  charges: new Set(["name", "actions"]),
  shares: new Set(["effectiveFrom", "actions"]),
  business: new Set(["select", "business", "actions"]),
  shareApplications: new Set(["select", "application", "actions"]),
  procurement: new Set(["select", "request", "actions"]),
  foodPurchase: new Set(["select", "application", "actions"]),
  projectFinancing: new Set(["select", "request", "actions"]),
  support: new Set(["select", "case", "actions"]),
  paymentReceipts: new Set(["select", "receipt", "actions"]),
  chargeLibrary: new Set(["charge", "actions"]),
  imports: new Set(["import", "actions"]),
  loanPortfolio: new Set(["member", "actions"]),
  loanRequests: new Set(["member", "actions"]),
  membershipApprovals: new Set(["applicant", "actions"]),
  monthlyRecords: new Set(["member", "actions"]),
  notifications: new Set(["subject", "actions"]),
  audit: new Set(["action", "actions"]),
}

export const ROW_HEIGHTS: Record<TableId, number> = {
  members: 56,
  contributions: 56,
  charges: 56,
  shares: 56,
  business: 56,
  shareApplications: 64,
  procurement: 72,
  foodPurchase: 72,
  projectFinancing: 72,
  support: 72,
  paymentReceipts: 64,
  chargeLibrary: 56,
  imports: 56,
  loanPortfolio: 72,
  loanRequests: 84,
  membershipApprovals: 64,
  monthlyRecords: 64,
  notifications: 56,
  audit: 56,
}

export const SUMMARY_GRID_HEIGHTS: Partial<Record<TableId, number>> = {
  members: 180,
  contributions: 180,
  charges: 180,
  shares: 180,
  business: 180,
  shareApplications: 180,
  procurement: 180,
  foodPurchase: 180,
  projectFinancing: 180,
  support: 180,
  paymentReceipts: 180,
  chargeLibrary: 180,
  loanPortfolio: 180,
  loanRequests: 180,
  monthlyRecords: 180,
}

export const TABLE_CONFIGS: Record<TableId, TableConfig> = {
  members: {
    tableId: "members",
    stickyColumns: STICKY_COLUMNS.members,
    sortFieldMap: SORT_FIELD_MAPS.members,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.members,
    rowHeight: ROW_HEIGHTS.members,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.members,
  },
  contributions: {
    tableId: "contributions",
    stickyColumns: STICKY_COLUMNS.contributions,
    sortFieldMap: SORT_FIELD_MAPS.contributions,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.contributions,
    rowHeight: ROW_HEIGHTS.contributions,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.contributions,
  },
  charges: {
    tableId: "charges",
    stickyColumns: STICKY_COLUMNS.charges,
    sortFieldMap: SORT_FIELD_MAPS.charges,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.charges,
    rowHeight: ROW_HEIGHTS.charges,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.charges,
  },
  shares: {
    tableId: "shares",
    stickyColumns: STICKY_COLUMNS.shares,
    sortFieldMap: SORT_FIELD_MAPS.shares,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.shares,
    rowHeight: ROW_HEIGHTS.shares,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.shares,
  },
  business: {
    tableId: "business",
    stickyColumns: STICKY_COLUMNS.business,
    sortFieldMap: SORT_FIELD_MAPS.business,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.business,
    rowHeight: ROW_HEIGHTS.business,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.business,
  },
  shareApplications: {
    tableId: "shareApplications",
    stickyColumns: STICKY_COLUMNS.shareApplications,
    sortFieldMap: SORT_FIELD_MAPS.shareApplications,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.shareApplications,
    rowHeight: ROW_HEIGHTS.shareApplications,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.shareApplications,
  },
  procurement: {
    tableId: "procurement",
    stickyColumns: STICKY_COLUMNS.procurement,
    sortFieldMap: SORT_FIELD_MAPS.procurement,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.procurement,
    rowHeight: ROW_HEIGHTS.procurement,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.procurement,
  },
  foodPurchase: {
    tableId: "foodPurchase",
    stickyColumns: STICKY_COLUMNS.foodPurchase,
    sortFieldMap: SORT_FIELD_MAPS.foodPurchase,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.foodPurchase,
    rowHeight: ROW_HEIGHTS.foodPurchase,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.foodPurchase,
  },
  projectFinancing: {
    tableId: "projectFinancing",
    stickyColumns: STICKY_COLUMNS.projectFinancing,
    sortFieldMap: SORT_FIELD_MAPS.projectFinancing,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.projectFinancing,
    rowHeight: ROW_HEIGHTS.projectFinancing,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.projectFinancing,
  },
  support: {
    tableId: "support",
    stickyColumns: STICKY_COLUMNS.support,
    sortFieldMap: SORT_FIELD_MAPS.support,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.support,
    rowHeight: ROW_HEIGHTS.support,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.support,
  },
  paymentReceipts: {
    tableId: "paymentReceipts",
    stickyColumns: STICKY_COLUMNS.paymentReceipts,
    sortFieldMap: SORT_FIELD_MAPS.paymentReceipts,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.paymentReceipts,
    rowHeight: ROW_HEIGHTS.paymentReceipts,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.paymentReceipts,
  },
  chargeLibrary: {
    tableId: "chargeLibrary",
    stickyColumns: STICKY_COLUMNS.chargeLibrary,
    sortFieldMap: SORT_FIELD_MAPS.chargeLibrary,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.chargeLibrary,
    rowHeight: ROW_HEIGHTS.chargeLibrary,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.chargeLibrary,
  },
  imports: {
    tableId: "imports",
    stickyColumns: STICKY_COLUMNS.imports,
    sortFieldMap: SORT_FIELD_MAPS.imports,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.imports,
    rowHeight: ROW_HEIGHTS.imports,
  },
  loanPortfolio: {
    tableId: "loanPortfolio",
    stickyColumns: STICKY_COLUMNS.loanPortfolio,
    sortFieldMap: SORT_FIELD_MAPS.loanPortfolio,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.loanPortfolio,
    rowHeight: ROW_HEIGHTS.loanPortfolio,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.loanPortfolio,
  },
  loanRequests: {
    tableId: "loanRequests",
    stickyColumns: STICKY_COLUMNS.loanRequests,
    sortFieldMap: SORT_FIELD_MAPS.loanRequests,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.loanRequests,
    rowHeight: ROW_HEIGHTS.loanRequests,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.loanRequests,
  },
  membershipApprovals: {
    tableId: "membershipApprovals",
    stickyColumns: STICKY_COLUMNS.membershipApprovals,
    sortFieldMap: SORT_FIELD_MAPS.membershipApprovals,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.membershipApprovals,
    rowHeight: ROW_HEIGHTS.membershipApprovals,
  },
  monthlyRecords: {
    tableId: "monthlyRecords",
    stickyColumns: STICKY_COLUMNS.monthlyRecords,
    sortFieldMap: SORT_FIELD_MAPS.monthlyRecords,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.monthlyRecords,
    rowHeight: ROW_HEIGHTS.monthlyRecords,
    summaryGridHeight: SUMMARY_GRID_HEIGHTS.monthlyRecords,
  },
  notifications: {
    tableId: "notifications",
    stickyColumns: STICKY_COLUMNS.notifications,
    sortFieldMap: SORT_FIELD_MAPS.notifications,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.notifications,
    rowHeight: ROW_HEIGHTS.notifications,
  },
  audit: {
    tableId: "audit",
    stickyColumns: STICKY_COLUMNS.audit,
    sortFieldMap: SORT_FIELD_MAPS.audit,
    nonReorderableColumns: NON_REORDERABLE_COLUMNS.audit,
    rowHeight: ROW_HEIGHTS.audit,
  },
}

export function getTableConfig(tableId: TableId): TableConfig {
  return TABLE_CONFIGS[tableId]
}
